### ISSUE TITLE
[Bug] Wrong page while selecting the page number

### ISSUE THREAD

**Issue by bruce30262** [bamboofox/bamboofox-blog-old#1]
If we enter page 2 ( [https://bamboofox.github.io/page2/](https://bamboofox.github.io/page2/) )  , then click page 3 in the page num bar , 
the URL will become [https://bamboofox.github.io/page2/page3](https://bamboofox.github.io/page2/page3), causing the website returns a 404 not found error.

**Comment by oalieno** [comment]
@bruce30262 
這個 bugs 修掉了喔 #3 
是 baseurl 的問題
可以再去看一下有沒有問題~
