### ISSUE TITLE
Some questions about the website

### ISSUE THREAD

**Issue by bruce30262** [bamboofox/bamboofox-blog-old#2]
Since the website has migrated from hexo to jekyll, I have some questions about the website & the repository:  

1. Will this be the official repository of the [bamboofox.github.io](bamboofox.github.io) website?  
2. Any manual for how to contribute write-ups for the website?  
3. Will there be a docker image for the current website ? ( like the previous one in [old-blog](https://github.com/bamboofox/old-blog/tree/master/docker) )  

I'm asking these because I would like to take some time to reformat my write-ups in the blog, since they do not fit well in the current theme ( especially the code blocks part ), which make those write-ups hard to read :dizzy_face:

**Comment by bananaappletw** [comment]
1. Yes
Github support jekyll [build from branch](https://help.github.com/articles/about-github-pages-and-jekyll/#jekylls-build-process).
Unlike [old-blog](https://github.com/bamboofox/old-blog), which needs two separate repositories, one for site generator one for static site.
This is one of reasons why we migrated from hexo to jekyll.
2. @OAlienO 
3. @OAlienO 

Migration is in progress.
There are still many problems to solve.
Thanks for the reminder

**Comment by oalieno** [comment]
@bruce30262 
我更新了 README.md ( 040cee6 )
加了 Docker Support 和 Contribute 的說明

**Comment by bruce30262** [comment]
@OAlienO  :+1: 
再問一下，jekyll 是我們直接改完 _post 裡面的文章然後 push 到 github 就可以了嗎 ?
還是說需要像 hexo 一樣要 `hexo deploy` 之類的 ?

**Comment by bananaappletw** [comment]
@bruce30262 
對的
直接推上去它就會幫你 build
要稍微等一下
github 會幫你跑
