### ISSUE TITLE
code block 的 theme 怪怪的

### ISSUE THREAD

**Issue by bruce30262** [bamboofox/bamboofox-blog-old#5]
scroll bar 變兩條 O_o

<img width="511" alt="default" src="https://user-images.githubusercontent.com/4478350/32895457-1d5cd4fa-cb1b-11e7-8425-5c4d51a91afb.PNG">

**Comment by bruce30262** [comment]
@OAlienO  bump  
最近這邊好像有點沉寂 @@

**Comment by oalieno** [comment]
喔抱歉沒有看到 Issue @@
我研究一下發生什麼事了

**Comment by oalieno** [comment]
https://github.com/kaeyleo/jekyll-theme-H2O/issues/27
不知道是不是他的 theme 的問題O_O?
不過我先暫時修補好了~

**Comment by bruce30262** [comment]
@OAlienO  👍 
是說 blog 最近好像沒啥更新? 覺得可以更新一下課程資訊(投影片, 直播)之類的  
社員們也比較好找資源  
( 只是題外囉嗦一下 XD 這 issue 就先 close 掉了 )
